name = "mindx-staff-hub"
main = ".open-next/worker.js"
compatibility_date = "2026-08-28"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"

[build]
command = "npx opennextjs-cloudflare build"

[vars]
LMS_BASE_URL = "https://base-api.mindx.edu.vn/"
LMS_GATEWAY_URL = "https://lms-api.mindx.edu.vn/"
LMS_ORIGIN = "https://lms.mindx.edu.vn"
LMS_REFERER = "https://lms.mindx.edu.vn/"
NEXT_PUBLIC_DEFAULT_CENTRE_IDS = "6443460f94300678908f7974"
